export const PropertyType = [
  { value: "casas", name: "Casas" },
  { value: "apartamentos", name: "Apartamentos" },
  { name: "Terrenos", value: "terreno" },
  { name: "Locales", value: "local" },
  { name: "Oficinas", value: "oficina" },
]

export const ListType = [
  { value: "ventas", name: "Venta" },
  { value: "alquileres", name: "Alquiler" },
]

export const ZoneType = [
  {
    label: "Abayuba - colon sudeste",
    value: "abayuba - colon sudeste",
    zone: "montevideo",
  },
  { label: "Aguada", value: "aguada", zone: "montevideo" },
  { label: "Aires Puros", value: "aires puros", zone: "montevideo" },
  { label: "Arroyo Seco", value: "arroyo seco", zone: "montevideo" },
  { label: "Atahualpa", value: "atahualpa", zone: "montevideo" },
  {
    label: "Barra Santa Lucia",
    value: "barra santa lucia",
    zone: "montevideo",
  },
  { label: "Barrio Sur", value: "barrio sur", zone: "montevideo" },
  { label: "Bella Italia", value: "bella italia", zone: "montevideo" },
  { label: "Bella Vista", value: "bella vista", zone: "montevideo" },
  { label: "Belvedere", value: "belvedere", zone: "montevideo" },
  { label: "Bolivar", value: "bolivar", zone: "montevideo" },
  {
    label: "Bañados de Carrasco",
    value: "bañados de carrasco",
    zone: "montevideo",
  },
  { label: "Brazo Oriental", value: "brazo oriental", zone: "montevideo" },
  { label: "Buceo", value: "buceo", zone: "montevideo" },
  { label: "Capurro", value: "capurro", zone: "montevideo" },
  { label: "Carrasco", value: "carrasco", zone: "montevideo" },
  { label: "Carrasco Norte", value: "carrasco norte", zone: "montevideo" },
  { label: "Casabo", value: "casabo", zone: "montevideo" },
  { label: "Casavalle", value: "casavalle", zone: "montevideo" },
  { label: "Centro", value: "centro", zone: "montevideo" },
  { label: "Cerrito", value: "cerrito", zone: "montevideo" },
  { label: "Cerro", value: "cerro", zone: "montevideo" },
  { label: "Cerro Norte", value: "cerro norte", zone: "montevideo" },
  { label: "Ciudad Vieja", value: "ciudad vieja", zone: "montevideo" },
  { label: "Camino Carrasco", value: "camino carrasco", zone: "montevideo" },
  { label: "Camino Maldonado", value: "camino maldonado", zone: "montevideo" },
  { label: "Colon", value: "colon", zone: "montevideo" },
  { label: "Conciliacion", value: "conciliacion", zone: "montevideo" },
  { label: "Cordon", value: "cordon", zone: "montevideo" },
  { label: "Goes", value: "goes", zone: "montevideo" },
  { label: "Golf", value: "golf", zone: "montevideo" },
  { label: "Ituzaingo", value: "ituzaingo", zone: "montevideo" },
  { label: "J. Hipodromo", value: "j. hipodromo", zone: "montevideo" },
  { label: "Jacinto Vera", value: "jacinto vera", zone: "montevideo" },
  { label: "Joanico", value: "joanico", zone: "montevideo" },
  { label: "La Blanqueada", value: "la blanqueada", zone: "montevideo" },
  { label: "La Comercial", value: "la comercial", zone: "montevideo" },
  { label: "La Figurita", value: "la figurita", zone: "montevideo" },
  { label: "La Paloma", value: "la paloma", zone: "montevideo" },
  { label: "La Teja", value: "la teja", zone: "montevideo" },
  { label: "Larrañaga", value: "larrañaga", zone: "montevideo" },
  { label: "Lavalleja", value: "lavalleja", zone: "montevideo" },
  { label: "Las Acacias", value: "las acacias", zone: "montevideo" },
  { label: "Las Canteras", value: "las canteras", zone: "montevideo" },
  {
    label: "Lezica",
    value: "lezica",
    zone: "montevideo",
  },
  {
    label: "Malvin",
    value: "malvin",
    zone: "montevideo",
  },
  {
    label: "Malvin Norte",
    value: "malvin norte",
    zone: "montevideo",
  },
  {
    label: "Manga",
    value: "manga",
    zone: "montevideo",
  },
  {
    label: "Marconi",
    value: "marconi",
    zone: "montevideo",
  },
  {
    label: "Maroñas",
    value: "maroñas",
    zone: "montevideo",
  },
  {
    label: "Maroñas Curva",
    value: "maroñas curva",
    zone: "montevideo",
  },
  {
    label: "Melilla",
    value: "melilla",
    zone: "montevideo",
  },
  {
    label: "Nuevo Centro",
    value: "nuevo centro",
    zone: "montevideo",
  },
  {
    label: "Nuevo Paris",
    value: "nuevo paris",
    zone: "montevideo",
  },
  {
    label: "Otros",
    value: "otros",
    zone: "montevideo",
  },
  {
    label: "Pajas Blancas",
    value: "pajas blancas",
    zone: "montevideo",
  },
  {
    label: "Palermo",
    value: "palermo",
    zone: "montevideo",
  },
  {
    label: "Parque Batlle",
    value: "parque batlle",
    zone: "montevideo",
  },
  {
    label: "Parque Guarani",
    value: "parque guarani",
    zone: "montevideo",
  },
  {
    label: "Parque Rodo",
    value: "parque rodo",
    zone: "montevideo",
  },
  {
    label: "Paso de las Duranas",
    value: "paso de las duranas",
    zone: "montevideo",
  },
  {
    label: "Paso Carrasco",
    value: "paso carrasco",
    zone: "montevideo",
  },
  {
    label: "Paso de la arena",
    value: "paso de la arena",
    zone: "montevideo",
  },
  {
    label: "Paso Molino",
    value: "paso molino",
    zone: "montevideo",
  },
  {
    label: "Peñarol",
    value: "peñarol",
    zone: "montevideo",
  },
  {
    label: "Perez Castellanos",
    value: "perez castellanos",
    zone: "montevideo",
  },
  {
    label: "Piedras Blancas",
    value: "piedras blancas",
    zone: "montevideo",
  },
  {
    label: "Pocitos",
    value: "pocitos",
    zone: "montevideo",
  },
  {
    label: "Pocitos Nuevo",
    value: "pocitos nuevo",
    zone: "montevideo",
  },
  {
    label: "Prado",
    value: "prado",
    zone: "montevideo",
  },
  {
    label: "Prado Norte",
    value: "prado norte",
    zone: "montevideo",
  },
  {
    label: "Puerto Buceo",
    value: "puerto buceo",
    zone: "montevideo",
  },
  {
    label: "Punta Carretas",
    value: "punta carretas",
    zone: "montevideo",
  },
  {
    label: "Punta Gorda",
    value: "punta gorda",
    zone: "montevideo",
  },
  {
    label: "Punta Rieles",
    value: "punta rieles",
    zone: "montevideo",
  },
  {
    label: "Reducto",
    value: "reducto",
    zone: "montevideo",
  },
  { label: "Sayago", value: "sayago", zone: "montevideo" },
  { label: "Santa Catalina", value: "santa catalina", zone: "montevideo" },
  { label: "Toledo Chico", value: "toledo chico", zone: "montevideo" },
  { label: "Tres Cruces", value: "tres cruces", zone: "montevideo" },
  { label: "Tres Ombues", value: "tres ombues", zone: "montevideo" },
  { label: "Union", value: "union", zone: "montevideo" },
  { label: "Villa Biarritz", value: "villa biarritz", zone: "montevideo" },
  { label: "Villa Dolores", value: "villa dolores", zone: "montevideo" },
  { label: "Villa Española", value: "villa española", zone: "montevideo" },
  { label: "Villa Garcia", value: "villa garcia", zone: "montevideo" },
  { label: "Villa Muñoz", value: "villa muñoz", zone: "montevideo" },

  
  { zone: "canelones",label: "Aeroparque", value: "aeroparque" },
  { zone: "canelones",label: "Aguas Corrientes", value: "aguas corrientes" },
  { zone: "canelones",label: "Araminda", value: "araminda" },
  { zone: "canelones",label: "Atlantida Norte", value: "atlantida norte" },
  { zone: "canelones",label: "Atlantida Sur", value: "atlantida sur" },
  { zone: "canelones",label: "Balneario Argentino", value: "balneario argentino" },
  { zone: "canelones",label: "Balneario Paraiso Suizo", value: "balneario paraiso suizo" },
  { zone: "canelones",label: "Bañado de Medina", value: "bañado de medina" },
  { zone: "canelones",label: "Barra de Carrasco", value: "barra de carrasco" },
  { zone: "canelones",label: "Barrios Privados", value: "barrios privados" },
  { zone: "canelones",label: "Barros Blancos", value: "barros blancos" },
  { zone: "canelones",label: "Bello Horizionte", value: "bello horizionte" },
  { zone: "canelones",label: "Biarritz", value: "biarritz" },
  { zone: "canelones",label: "Canelones", value: "canelones" },
  { zone: "canelones",label: "Cerrillos", value: "cerrillos" },
  { zone: "canelones",label: "Ciudad de la Costa", value: "ciudad de la costa" },
  { zone: "canelones",label: "Colinas de Solymar", value: "colinas de solymar" },
  { zone: "canelones",label: "Colonia Nicolich", value: "colonia nicolich" },
  { zone: "canelones",label: "Costa Azul", value: "costa azul" },
  { zone: "canelones",label: "Cuchilla Alta", value: "cuchilla alta" },
  { zone: "canelones",label: "El Bosque", value: "el bosque" },
  { zone: "canelones",label: "El Colorado", value: "el colorado" },
  { zone: "canelones",label: "El Dorado", value: "el dorado" },
  { zone: "canelones",label: "El Pinar", value: "el pinar" },
  { zone: "canelones",label: "Empalme Olmos", value: "empalme olmos" },
  { zone: "canelones",label: "Estacion Pedrera", value: "estacion pedrera" },
  { zone: "canelones",label: "Fortin de Santa Rosa", value: "fortin de santa rosa" },
  { zone: "canelones",label: "Guazuvirá", value: "guazuvirá" },
  { zone: "canelones",label: "Guazuvira Nuevo", value: "guazuvira nuevo" },
  { zone: "canelones",label: "Haras del Lago", value: "haras del lago" },
  { zone: "canelones",label: "Jaureguiberry", value: "jaureguiberry" },
  { zone: "canelones",label: "Joaquin Suarez", value: "joaquin suarez" },
  { zone: "canelones",label: "Juan Antonio Artigas", value: "juan antonio artigas" },
  {zone: "canelones", label: "Juanico", value: "juanico" },
  { zone: "canelones",label: "La Floresta", value: "la floresta" },
  {zone: "canelones", label: "La Paz", value: "la paz" },
  {zone: "canelones", label: "La Tahona", value: "la tahona" },
  {zone: "canelones", label: "La Tuna ", value: "la tuna " },
  {zone: "canelones", label: "Lagomar", value: "lagomar" },
  {zone: "canelones", label: "Las Brujas", value: "las brujas" },
  {zone: "canelones", label: "Las Piedras", value: "las piedras" },
  {zone: "canelones", label: "Las Toscas", value: "las toscas" },
  {zone: "canelones", label: "Las Vegas", value: "las vegas" },
  {zone: "canelones", label: "Lomas de Solymar", value: "lomas de solymar" },
  {zone: "canelones", label: "Los Cerrillos", value: "los cerrillos" },
  {zone: "canelones", label: "Los Titanes", value: "los titanes" },
  {zone: "canelones", label: "Marindia ", value: "marindia " },
  {zone: "canelones", label: "Mata Siete", value: "mata siete" },
  {zone: "canelones", label: "Medanos de Solymar", value: "medanos de solymar" },
  {zone: "canelones", label: "Montes de Solymar ", value: "montes de solymar " },
  {zone: "canelones", label: "Migues ", value: "migues " },
  {zone: "canelones", label: "Neptunia", value: "neptunia" },
  {zone: "canelones", label: "Otros", value: "otros" },
  {zone: "canelones", label: "Pando ", value: "pando " },
  {zone: "canelones", label: "Parque de Carrasco", value: "parque de carrasco" },
  {zone: "canelones", label: "Parque de Solymar ", value: "parque de solymar " },
  {zone: "canelones", label: "Parque del Plata", value: "parque del plata" },
  {zone: "canelones", label: "Parque del Plata Norte ", value: "parque del plata norte " },
  {zone: "canelones", label: "Parque Miramar", value: "parque miramar" },
  {zone: "canelones", label: "Paso Carrasco ", value: "paso carrasco " },
  {zone: "canelones", label: "Piedras de Afilar", value: "piedras de afilar" },
  {zone: "canelones", label: "Pinamar ", value: "pinamar " },
  {zone: "canelones", label: "Pinares de Solymar", value: "pinares de solymar" },
  {zone: "canelones", label: "Progreso ", value: "progreso " },
  {zone: "canelones", label: "Pueblo Suizo ", value: "pueblo suizo " },
  {zone: "canelones", label: "Salinas", value: "salinas" },
  {zone: "canelones", label: "San Antonio", value: "san antonio" },
  {zone: "canelones", label: "San Bautista ", value: "san bautista " },
  {zone: "canelones", label: "San Cristobal", value: "san cristobal" },
  {zone: "canelones", label: "San Jacinto", value: "san jacinto" },
  {zone: "canelones", label: "San Jose de Carrasco ", value: "san jose de carrasco " },
  {zone: "canelones", label: "San Luis", value: "san luis" },
  {zone: "canelones", label: "San Ramon ", value: "san ramon " },
  {zone: "canelones", label: "Santa Ana ", value: "santa ana " },
  {zone: "canelones", label: "Santa Lucia ", value: "santa lucia " },
  {zone: "canelones", label: "Santa Lucia del Este ", value: "santa lucia del este " },
  {zone: "canelones", label: "Santa Rosa", value: "santa rosa" },
  {zone: "canelones", label: "Sauce", value: "sauce" },
  {zone: "canelones", label: "Shangrilá", value: "shangrilá" },
  {zone: "canelones", label: "Sierra del Mar", value: "sierra del mar" },
  {zone: "canelones", label: "Soca", value: "soca" },
  {zone: "canelones", label: "Solis Chico", value: "solis chico" },
  {zone: "canelones", label: "Solymar", value: "solymar" },
  {zone: "canelones", label: "Suárez", value: "suárez" },
  {zone: "canelones", label: "Tala", value: "tala" },
  {zone: "canelones", label: "Toledo", value: "toledo" },
  {zone: "canelones", label: "Totoral", value: "totoral" },
  {zone: "canelones", label: "Villa Aeroparque ", value: "villa aeroparque " },
  {zone: "canelones", label: "Villa Argentina ", value: "villa argentina " },
  {zone: "canelones", label: "Villa Crespo", value: "villa crespo" },
  {zone: "canelones", label: "Villa El Tato", value: "villa el tato" },
  {zone: "canelones", label: "Villa Felicidad", value: "villa felicidad" },
  {zone: "canelones", label: "Villa San Jose", value: "villa san jose" },
  {zone: "canelones", label: "Vista Linda", value: "vista linda" },
  {zone: "canelones", label: "Zona Rural", value: "zona rural" },
]

export const StateType = [
  { value: "Montevideo", name: "Montevideo" },
  { value: "Canelones", name: "Canelones" },
]

export const Currency = [
  { value: "U$S", name: "U$S" },
  { value: "$", name: "$" },
]

export const MinPrice = [
  { value: "1000", name: "1.000" },
  { value: "50000", name: "50.000" },
  { value: "100000", name: "100.000" },
  { value: "150000", name: "150.000" },
  { value: "200000", name: "200.000" },
  { value: "250000", name: "250.000" },
  { value: "300000", name: "300.000" },
  { value: "400000", name: "400.000" },
  { value: "450000", name: "450.000" },
  { value: "500000", name: "500.000" },
  { value: "550000", name: "550.000" },
  { value: "600000", name: "600.000" },
  { value: "750000", name: "750.000" },
  { value: "800000", name: "800.000" },
  { value: "950000", name: "950.000" },
  { value: "1000000", name: "1.000.000" },
]

export const MaxPrice = [
  { value: "1000", name: "1.000" },
  { value: "50000", name: "50.000" },
  { value: "100000", name: "100.000" },
  { value: "150000", name: "150.000" },
  { value: "200000", name: "200.000" },
  { value: "250000", name: "250.000" },
  { value: "300000", name: "300.000" },
  { value: "400000", name: "400.000" },
  { value: "450000", name: "450.000" },
  { value: "500000", name: "500.000" },
  { value: "550000", name: "550.000" },
  { value: "600000", name: "600.000" },
  { value: "750000", name: "750.000" },
  { value: "800000", name: "800.000" },
  { value: "950000", name: "950.000" },
  { value: "1000000", name: "1.000.000" },
]
