export const PropertyType = [
  { value: "casas", name: "Casas" },
  { value: "apartamentos", name: "Apartamentos" },
  { name: "Terreno", value: "terreno" },
  { name: "Local", value: "local" },
  { name: "Oficina", value: "oficina" },
]

export const ListType = [
  { value: "ventas", name: "Ventas" },
  { value: "alquileres", name: "Alquileres" },
]

export const ZoneType = [
  { value: "Villa Biarritz", name: "villa biarritz" },
  { value: "Pocitos", name: "pocitos" },
  { value: "Parque Rodó", name: "parque rodó" },
  { value: "Parque Batlle", name: "parque batlle" },
  { value: "Buceo", name: "buceo" },
  { value: "Nuevo pocitos", name: "nuevo pocitos" },
  { value: "Cordón", name: "cordón" },
  { value: "Tres cruces", name: "tres cruces" },
  { value: "Punta Carretas", name: "punta carretas" },
  { value: "Barrio Sur", name: "barrio sur" },
  { value: "Centro", name: "centro" },
  { value: "Ciudad Vieja", name: "ciudad vieja" },
  { value: "Larrañaga", name: "larrañaga" },
  { value: "Jacinto Vera", name: "jacinto vera" },
  { value: "Goes", name: "goes" },
  { value: "Aguada", name: "aguada" },
  { value: "Villa Muñoz", name: "villa muñoz" },
  { value: "Reducto", name: "reducto" },
  { value: "Bella Vista", name: "bella vista" },
  { value: "Prado", name: "prado" },
  { value: "Atahualpa", name: "atahualpa" },
  { value: "Arroyo Seco", name: "arroyo seco" },
  { value: "La comercial", name: "la comercial" },
  { value: "La Figurita", name: "la figurita" },
  { value: "Palermo", name: "palermo" },
  { value: "La Blanqueada", name: "la blanqueada" },
  {value: 'Union', name:'union'},
  {value: "Malvín", name:'malvin'},
  {value: "Malvín Norte", name:'malvin norte'},
  {value:"Las Canteras", name:"las canteras"},
  {value:"Punta Gorda", name:"punta gorda"},
  {value: "Carrasco", name:'carrasco'},
  {value: "Carrasco Norte", name:'carrasco norte'},
  {value: "Bañados de Carrasco", name:'bañados de carrasco'},
  {value: "Flor de Maroñas", name:'flor de maroñas'},
  {value: "Maroñas–Parque", name:'maroñas–parque'},
  {value: "Villa Española", name:'villa española'},
  {value: "Ituzaingó", name:'ituzaingó'},
  {value: "Castro–Pérez", name:'castro–pérez'},
  {value: "Mercado Modelo–Bolívar", name:'mercado modelo–bolívar'},
  {value: "Brazo Oriental", name:'brazo oriental'},
  {value: "Prado–Nueva", name:'prado–nueva'},
  {value: "Aires Puros", name:'aires puros'},
  {value: "Paso de las Duranas", name:'paso de las duranas'},
  {value: "Belvedere", name:'belvedere'},
  {value: "La Teja", name:'la teja'},
  {value: "Tres Ombúes–Pueblo", name:'tres ombúes–pueblo'},
  {value: "Villa del Cerro", name:'villa del cerro'},
  {value: "Casabó–Pajas Blancas", name:'casabó–Pajas blancas'},
  {value: "La Paloma–Tomkinson", name:'la paloma–tomkinson'},
  {value: "Paso de la Arena–Santiago Vázquez", name:'paso de la arena–santiago vázquez'},
  {value: "Nuevo París", name:'nuevo parís'},
  {value: "Conciliación", name:'conciliación'},
  {value: "Sayago", name:'sayago'},
  {value: "Peñarol–Lavalleja", name:'peñarol–lavalleja'},
  {value: "Lezica–Melilla", name:'lezica–melilla'},
  {value:"Colón Sudeste–Abayubá", name:"colón sudeste–abayubá"},
  {value:"Manga–Toledo Chico", name:"manga–toledo chico"},
  {value:"Casavalle", name:"casavalle"},
  {value:"Cerrito de la Victoria", name:"cerrito de la victoria"},
  {value:"Las Acacias", name:"las acacias"},
  {value:"Jardines del Hipódromo", name:"jardines del hipódromo"},
  {value:"Piedras Blancas", name:"piedras blancas"},
  {value:"Manga", name:"manga"},
  {value:"Punta de Rieles – Bella Italia", name:"punta de rieles – bella italia"},
  {value:"Villa García–Manga Rural", name:"villa garcía–manga rural"},
]

export const StateType = [
  { value: "Montevideo", name: "montevideo" },
  { value: "Canelones", name: "canelones" },
]

export const Currency = [
  { value: "U$S", name: "U$S" },
  { value: "$", name: "$" },
]

export const MinPrice = [
  { value: "1000", name: "1.000" },
  { value: "50000", name: "50.000" },
  { value: "100000", name: "100.000" },
  { value: "150000", name: "150.000" },
  { value: "200000", name: "200.000" },
  { value: "250000", name: "250.000" },
  { value: "300000", name: "300.000" },
  { value: "400000", name: "400.000" },
  { value: "450000", name: "450.000" },
  { value: "500000", name: "500.000" },
  { value: "550000", name: "550.000" },
  { value: "600000", name: "600.000" },
  { value: "750000", name: "750.000" },
  { value: "800000", name: "800.000" },
  { value: "950000", name: "950.000" },
  { value: "1000000", name: "1.000.000" },
]

export const MaxPrice = [
  { value: "1000", name: "1.000" },
  { value: "50000", name: "50.000" },
  { value: "100000", name: "100.000" },
  { value: "150000", name: "150.000" },
  { value: "200000", name: "200.000" },
  { value: "250000", name: "250.000" },
  { value: "300000", name: "300.000" },
  { value: "400000", name: "400.000" },
  { value: "450000", name: "450.000" },
  { value: "500000", name: "500.000" },
  { value: "550000", name: "550.000" },
  { value: "600000", name: "600.000" },
  { value: "750000", name: "750.000" },
  { value: "800000", name: "800.000" },
  { value: "950000", name: "950.000" },
  { value: "1000000", name: "1.000.000" },
]
