export const PropertyType = [
  { value: "casas", name: "Casas" },
  { value: "apartamentos", name: "Apartamentos" },
  { name: "Terrenos", value: "terreno" },
  { name: "Locales", value: "local" },
  { name: "Oficinas", value: "oficina" },
]

export const ListType = [
  { value: "ventas", name: "Venta" },
  { value: "alquileres", name: "Alquiler" },
]

export const ZoneType = [
  { value: "Villa Biarritz", name: "villa biarritz", zone: "montevideo" },
  { value: "Pocitos", name: "pocitos", zone: "montevideo" },
  { value: "Parque Rodó", name: "parque rodó", zone: "montevideo" },
  { value: "Parque Batlle", name: "parque batlle", zone: "montevideo" },
  { value: "Buceo", name: "buceo", zone: "montevideo" },
  { value: "Nuevo pocitos", name: "nuevo pocitos", zone: "montevideo" },
  { value: "Cordón", name: "cordón", zone: "montevideo" },
  { value: "Tres cruces", name: "tres cruces", zone: "montevideo" },
  { value: "Punta Carretas", name: "punta carretas", zone: "montevideo" },
  { value: "Barrio Sur", name: "barrio sur", zone: "montevideo" },
  { value: "Centro", name: "centro", zone: "montevideo" },
  { value: "Ciudad Vieja", name: "ciudad vieja", zone: "montevideo" },
  { value: "Larrañaga", name: "larrañaga", zone: "montevideo" },
  { value: "Jacinto Vera", name: "jacinto vera", zone: "montevideo" },
  { value: "Goes", name: "goes", zone: "montevideo" },
  { value: "Aguada", name: "aguada", zone: "montevideo" },
  { value: "Villa Muñoz", name: "villa muñoz", zone: "montevideo" },
  { value: "Reducto", name: "reducto", zone: "montevideo" },
  { value: "Bella Vista", name: "bella vista", zone: "montevideo" },
  { value: "Prado", name: "prado", zone: "montevideo" },
  { value: "Atahualpa", name: "atahualpa", zone: "montevideo" },
  { value: "Arroyo Seco", name: "arroyo seco", zone: "montevideo" },
  { value: "La comercial", name: "la comercial", zone: "montevideo" },
  { value: "La Figurita", name: "la figurita", zone: "montevideo" },
  { value: "Palermo", name: "palermo" , zone: "montevideo"},
  { value: "La Blanqueada", name: "la blanqueada" , zone: "montevideo"},
  {value: 'Union', name:'union', zone: "montevideo"},
  {value: "Malvín", name:'malvin', zone: "montevideo"},
  {value: "Malvín Norte", name:'malvin norte', zone: "montevideo"},
  {value:"Las Canteras", name:"las canteras", zone: "montevideo"},
  {value:"Punta Gorda", name:"punta gorda", zone: "montevideo"},
  {value: "Carrasco", name:'carrasco', zone: "montevideo"},
  {value: "Carrasco Norte", name:'carrasco norte'},
  {value: "Bañados de Carrasco", name:'bañados de carrasco', zone: "montevideo"},
  {value: "Flor de Maroñas", name:'flor de maroñas', zone: "montevideo"},
  {value: "Maroñas–Parque", name:'maroñas–parque', zone: "montevideo"},
  {value: "Villa Española", name:'villa española', zone: "montevideo"},
  {value: "Ituzaingó", name:'ituzaingó', zone: "montevideo"},
  {value: "Castro–Pérez", name:'castro–pérez', zone: "montevideo"},
  {value: "Mercado Modelo–Bolívar", name:'mercado modelo–bolívar', zone: "montevideo"},
  {value: "Brazo Oriental", name:'brazo oriental', zone: "montevideo"},
  {value: "Prado–Nueva", name:'prado–nueva', zone: "montevideo"},
  {value: "Aires Puros", name:'aires puros', zone: "montevideo"},
  {value: "Paso de las Duranas", name:'paso de las duranas', zone: "montevideo"},
  {value: "Belvedere", name:'belvedere', zone: "montevideo"},
  {value: "La Teja", name:'la teja', zone: "montevideo"},
  {value: "Tres Ombúes–Pueblo", name:'tres ombúes–pueblo', zone: "montevideo"},
  {value: "Villa del Cerro", name:'villa del cerro', zone: "montevideo"},
  {value: "Casabó–Pajas Blancas", name:'casabó–Pajas blancas', zone: "montevideo"},
  {value: "La Paloma–Tomkinson", name:'la paloma–tomkinson', zone: "montevideo"},
  {value: "Paso de la Arena–Santiago Vázquez", name:'paso de la arena–santiago vázquez', zone: "montevideo"},
  {value: "Nuevo París", name:'nuevo parís', zone: "montevideo"},
  {value: "Conciliación", name:'conciliación', zone: "montevideo"},
  {value: "Sayago", name:'sayago', zone: "montevideo"},
  {value: "Peñarol–Lavalleja", name:'peñarol–lavalleja', zone: "montevideo"},
  {value: "Lezica–Melilla", name:'lezica–melilla', zone: "montevideo"},
  {value:"Colón Sudeste–Abayubá", name:"colón sudeste–abayubá", zone: "montevideo"},
  {value:"Manga–Toledo Chico", name:"manga–toledo chico", zone: "montevideo"},
  {value:"Casavalle", name:"casavalle", zone: "montevideo"},
  {value:"Cerrito de la Victoria", name:"cerrito de la victoria", zone: "montevideo"},
  {value:"Las Acacias", name:"las acacias", zone: "montevideo"},
  {value:"Jardines del Hipódromo", name:"jardines del hipódromo", zone: "montevideo"},
  {value:"Piedras Blancas", name:"piedras blancas", zone: "montevideo"},
  {value:"Manga", name:"manga", zone: "montevideo"},
  {value:"Punta de Rieles – Bella Italia", name:"punta de rieles – bella italia", zone: "montevideo"},
  {value:"Villa García–Manga Rural", name:"villa garcía–manga rural", zone: "montevideo"},
  {value:"Lagomar", name:"lagomar", zone: 'canelones'},
  {value:"Solymar", name:"solymar", zone: 'canelones'},
  {value:"medanos de solymar", name:"medanos de solymar", zone: 'canelones'},
  {value:"lomas de solymar", name:"lomas de solymar", zone: 'canelones'},
  {value:"el pinar", name:"el pinar", zone: 'canelones'},
  {value:"colonia nicolich", name:"colonia nicolich", zone: 'canelones'},
  {value:"shangrila", name:"shangrila", zone: 'canelones'},
  {value:"paso carrasco", name:" paso carrasco", zone: 'canelones'},
  {value:"san josé de carrasco", name:"san josé de carrasco", zone: 'canelones'},
  {value:"ciudad de la costa", name:"ciudad de la costa", zone: 'canelones'},
  
]

export const StateType = [
  { value: "Montevideo", name: "Montevideo" },
  { value: "Canelones", name: "Canelones" },
]

export const Currency = [
  { value: "U$S", name: "U$S" },
  { value: "$", name: "$" },
]

export const MinPrice = [
  { value: "1000", name: "1.000" },
  { value: "50000", name: "50.000" },
  { value: "100000", name: "100.000" },
  { value: "150000", name: "150.000" },
  { value: "200000", name: "200.000" },
  { value: "250000", name: "250.000" },
  { value: "300000", name: "300.000" },
  { value: "400000", name: "400.000" },
  { value: "450000", name: "450.000" },
  { value: "500000", name: "500.000" },
  { value: "550000", name: "550.000" },
  { value: "600000", name: "600.000" },
  { value: "750000", name: "750.000" },
  { value: "800000", name: "800.000" },
  { value: "950000", name: "950.000" },
  { value: "1000000", name: "1.000.000" },
]

export const MaxPrice = [
  { value: "1000", name: "1.000" },
  { value: "50000", name: "50.000" },
  { value: "100000", name: "100.000" },
  { value: "150000", name: "150.000" },
  { value: "200000", name: "200.000" },
  { value: "250000", name: "250.000" },
  { value: "300000", name: "300.000" },
  { value: "400000", name: "400.000" },
  { value: "450000", name: "450.000" },
  { value: "500000", name: "500.000" },
  { value: "550000", name: "550.000" },
  { value: "600000", name: "600.000" },
  { value: "750000", name: "750.000" },
  { value: "800000", name: "800.000" },
  { value: "950000", name: "950.000" },
  { value: "1000000", name: "1.000.000" },
]
